version: "3.9"

services:

  tftp:
    image: danrue/tftpd-hpa:latest
    container_name: netboot_tftp
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./etc/tftp:/srv/tftp:ro
    command: ["/usr/sbin/in.tftpd", "-L", "--secure", "/srv/tftp"]

  http:
    image: nginx:alpine
    container_name: netboot_http
    restart: unless-stopped
    network_mode: host
    # ports:
    # - "0.0.0.0:${HTTP_PORT}:8067"
    volumes:
      - ./etc/http/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./etc/http/nocloud:/usr/share/nginx/html/nocloud:ro
      - ./iso:/usr/share/nginx/html/iso:ro
